create database ecommercedb;
use ecommercedb;

/*Creating Table for Supplier with fields SUPP_ID, SUPP_NAME, SUPP_CITY, SUPP_PHONE*/
CREATE TABLE IF NOT EXISTS supplier (
    SUPP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SUPP_Name VARCHAR(50) NOT NULL,
    SUPP_CITY VARCHAR(50),
    SUPP_PHONE VARCHAR(10) NOT NULL
);

/*Creating Table for Customer with fields CUS_ID, CUS_NAME, CUS_PHONE, CUS_CITY, CUS_GENDER*/
CREATE TABLE IF NOT EXISTS customer (
    CUS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUS_NAME VARCHAR(20) NOT NULL,
    CUS_PHONE VARCHAR(10) NULL,
    CUS_CITY VARCHAR(30) NOT NULL,
    CUS_GENDER CHAR
);
 
/*Creating Table for Category with fields CAT_ID, CAT_NAME*/
CREATE TABLE IF NOT EXISTS category (
    CAT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CAT_NAME VARCHAR(20) NOT NULL
);

/*Creating Table for Product with fields PRO_ID, PRO_NAME, PRO_DESC, CAT_ID*/
CREATE TABLE if NOT EXISTS product(
	PRO_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PRO_NAME VARCHAR(20) NOT NULL DEFAULT('Dummy'),
	PRO_DESC VARCHAR(60),
	CAT_ID INT,
	FOREIGN KEY(CAT_ID) REFERENCES category(CAT_ID)
);

/*Creating Table for supplier_pricing with fields PRICING_ID, PRO_ID, SUPP_ID, SUPP_PRICE*/
CREATE TABLE IF NOT EXISTS supplier_pricing (
    PRICING_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRO_ID INT,
    SUPP_ID INT,
    SUPP_PRICE INT DEFAULT 0,
    FOREIGN KEY (PRO_ID)
        REFERENCES product (PRO_ID),
    FOREIGN KEY (SUPP_ID)
        REFERENCES supplier (SUPP_ID)
);

/*Creating Table for order_table with fields ORD_ID, ORD_AMOUNT, ORD_DATE, CUS_ID, PRICING_ID*/
CREATE TABLE IF NOT EXISTS `order` (
    ORD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORD_AMOUNT INT NOT NULL,
    ORD_DATE DATE NOT NULL,
    CUS_ID INT,
    PRICING_ID INT,
    FOREIGN KEY (CUS_ID)
        REFERENCES customer (CUS_ID),
    FOREIGN KEY (PRICING_ID)
        REFERENCES supplier_pricing (PRICING_ID)
);

/*Creating Table for rating with fields RAT_ID, ORD_ID, RAT_RATSTARS*/
CREATE TABLE IF NOT EXISTS rating (
    RAT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORD_ID INT NOT NULL,
    RAT_RATSTARS INT NOT NULL,
    FOREIGN KEY (ORD_ID)
        REFERENCES `order` (ORD_ID)
);
